### PR TITLE
Add Jest testing suite for E2E testing

### PR DESCRIPTION
**Pull request by BerkhanBerkdemir**
Hi @santiesque!

I would like to introduce you to a long waited, no one was waiting, PR. Please take a look at the `__tests__` directory for which endpoints are tested. I am still working on making sure that I test each endpoint; however, `code/index.js` does not do that by default and I didn't want to write manual Axios code.

### CODE REVIEW

**Comment by santiesque** [comment]
Job well done, mate. Just from the commit timeline. 

Give me few days to go over both PRs

**Comment by BerkhanBerkdemir** [comment]
I just wanted to know the status of the PR. Did you have a chance to look it up, @santiesque?

**Comment by santiesque** [comment]
I'm not entirely happy with the test folders. Too many files with repetitive code. 

Not your fault. It was bad before your PRs.

Im going to redo that, and merge this PR. 

Going to take a fews weeks. 

Comment your NANO Address for bounty.

**Comment by BerkhanBerkdemir** [comment]
> I'm not entirely happy with the test folders. Too many files with repetitive code.
> Not your fault. It was bad before your PRs.

I wanted to separate scenarios like the previous one therefore in the new testing suite I leave it that way (I made some corrections as well). You can easily delete the old ones because the new testing suite is replacing them with using the source from this repository instead of making raw requests to nano.to. I would like to hear your thoughts.

**Comment by santiesque** [comment]
Check this out:

https://nano.to/status?json=true

Helps if you have a JSON Formatter Browser Extension.

I want all the test scenarios to be in a json object like so.

```
[
    {
        name: 'NANO API - Search',
        url: 'https://nano.to/search/esteban',
        check: (content) => content.includes("esteban"),
    },

    {
        name: 'NANO API - Price',
        url: 'https://nano.to/price',
        check: (content) => typeof content.price !== undefined,
    },

    {
        name: 'NANO API - Username',
        url: 'https://nano.to/name/moon',
        check: (content) => typeof content.expires !== undefined,
    },

    {
        name: 'NANO API - Account',
        url: 'https://nano.to/pending/moon',
        check: (content) => (typeof content == "array" || typeof content == "object"),
    },

    {
        name: 'NANO API - History',
        url: 'https://nano.to/history/moon',
        check: (content) => (typeof content == "array" || typeof content == "object"),
    },
]
```

Or something like that. 

I'll keep this PR open until then.

**Comment by santiesque** [comment]
Please new testing style.

https://github.com/formsend/nano/blob/main/test/index.js

Just have me this one. This is how we'll organize tests. index.js file will support command line arguments & can be imported as a module if needed, not there yet tho.

**Comment by BerkhanBerkdemir** [comment]
Then I am closing this since you made your own testing suite.

**Pull request closed without merging**
